## Data Types and Array Operations

#### Datatypes:

In [1]:
import numpy as np


In [2]:
example1=np.array([11,12])

In [3]:
#python assigns the data type
example1.dtype


dtype('int64')

In [4]:
example2=np.array([18.0,22.0])

In [5]:
example2.dtype

dtype('float64')

In [7]:
#you can also specify the data type
example3=np.array([89,87],dtype='int64')


In [8]:
example3.dtype


dtype('int64')

In [10]:
#forcing floats into intrgers
example4=np.array([1.2,3.5],dtype=np.int64)


In [11]:
print(example4)

[1 3]


In [12]:
print(example4.dtype)

int64


In [13]:
trial=np.array([7.9,8.0],dtype='int64')

In [14]:
print(trial)

[7 8]


In [15]:
#changing intergers into floats
example5=np.array([10,67],dtype='float64')

In [16]:
print(example5)

[10. 67.]


## Arithmetic Array Oerations

In [18]:
x=np.array([[20,30],[40,50]],dtype='int64')
y=np.array([[10.5,15.2],[8.6,7.9]],dtype='float64')

In [19]:
print(x)
print(y)

[[20 30]
 [40 50]]
[[10.5 15.2]
 [ 8.6  7.9]]


In [20]:
#Addition
print(x+y)


[[30.5 45.2]
 [48.6 57.9]]


In [21]:
# addiction can also be done this way
z=np.add(x,y)
print(z)

[[30.5 45.2]
 [48.6 57.9]]


In [22]:
#Subtarction 
print(x-y)

[[ 9.5 14.8]
 [31.4 42.1]]


In [23]:
sub2=np.subtract(x,y)
print(sub2)

[[ 9.5 14.8]
 [31.4 42.1]]


In [24]:
#Multplication 
print(x*y)

[[210. 456.]
 [344. 395.]]


In [25]:
mult2=np.multiply(x,y)

In [26]:
print(mult2)

[[210. 456.]
 [344. 395.]]


In [27]:
#Division
print(x/y)

[[1.9047619  1.97368421]
 [4.65116279 6.32911392]]


In [28]:
div2=np.divide(x,y)
print(div2)

[[1.9047619  1.97368421]
 [4.65116279 6.32911392]]


In [29]:
#Square Root
print(np.sqrt(x))

[[4.47213595 5.47722558]
 [6.32455532 7.07106781]]


In [30]:
print(np.square(x))

[[ 400  900]
 [1600 2500]]


In [32]:
#exponent(e**y)
print(np.exp(y))

[[3.63155027e+04 3.99278684e+06]
 [5.43165959e+03 2.69728233e+03]]
