## Boolean Indexing

###  Arrray Indexing for Changing Elements

In [2]:
import numpy as np
array_Bool=np.array([[1,2],[3,4],[5,6]])

In [3]:
print(array_Bool)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
#create a filter that has boolean for whether the elements meet the conditions
filter=(array_Bool>2)

In [5]:
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [6]:
type(filter)

numpy.ndarray

In [7]:
filter.dtype

dtype('bool')

In [8]:
#selecting elements that meet the criteria
print(array_Bool[filter])

[3 4 5 6]


In [9]:
array_Bool[array_Bool>3]

array([4, 5, 6])

In [10]:
#changing the values of the elements
array_Bool[array_Bool%2==0]+=100

In [11]:
print(array_Bool)

[[  1 102]
 [  3 104]
 [  5 106]]
