### Ndarray Indexing

#### Slice Indexing

In [1]:
import numpy as np

In [3]:
#a 3*4 rank 2 array
array_1=np.array([[2,3,4,5],[7,8,9,10],[12,13,14,15]])
print(array_1)

[[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]]


In [6]:
# creating a subarray that has the first 2 rows and 2 columns
array_1_slice=array_1[:2,1:3]
print(array_1_slice)

[[3 4]
 [8 9]]


In [7]:
print(array_1.shape)

(3, 4)


#### changing the modified array chanhes also the underlying array

In [20]:
print(array_1)

[[  2 600   4   5]
 [  7   8   9  10]
 [ 12  13  14  15]]


In [21]:
#before
array_1[0,1]

600

In [22]:
array_1_slice[0,1]=500

In [23]:
#after
print(array_1)

[[  2 600 500   5]
 [  7   8   9  10]
 [ 12  13  14  15]]


In [24]:
array_1_slice[0,0]=200

In [25]:
#after 
array_1[0,1]

200

####  To avoid this inconvience we have to create a copy while doing the slicing

In [26]:
#copy
print(array_1)


[[  2 200 500   5]
 [  7   8   9  10]
 [ 12  13  14  15]]


In [27]:
array_1_slice2=np.array(array_1[:2,1:])

In [28]:
array_1_slice2

array([[200, 500,   5],
       [  8,   9,  10]])

In [29]:
array_1_slice2[0,2]=6


In [30]:
print(array_1_slice2)

[[200 500   6]
 [  8   9  10]]


In [31]:
print(array_1)

[[  2 200 500   5]
 [  7   8   9  10]
 [ 12  13  14  15]]


## Using both Interger Indexing and Slice Indexing

In [32]:
new_array=np.array([[2,3,4,5],[7,8,9,10],[21,22,23,24]])

In [33]:
new_array

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [21, 22, 23, 24]])

In [37]:
# using interger indexing and slicing indexing alters the rank
new_array_slice=new_array[1,:]


In [36]:
# created a rank 1 array
print(new_array_slice)


[ 7  8  9 10]


In [38]:
print(new_array_slice.shape)

(4,)


In [39]:
#slicing alone does not  alter the rank of the array
new_array_slice2=new_array[1:,0:2]


In [40]:
#notice it is still rank 2
print(new_array_slice2)


[[ 7  8]
 [21 22]]


In [47]:
#another example
new_array_slice3=new_array[1:2]

In [46]:
print(new_array_slice3)

[[ 7  8  9 10]]


In [50]:
test_array=new_array[2]

In [51]:
print(test_array)

[21 22 23 24]


In [58]:
col_rank1=new_array[:,1]

In [59]:
print(new_array)


[[ 2  3  4  5]
 [ 7  8  9 10]
 [21 22 23 24]]


In [63]:
print(col_rank1)
print(col_rank1.shape)


[ 3  8 22]
(3,)


In [61]:
col_rank2=new_array[:,1:2]

In [64]:
print(col_rank2)
print(col_rank2.shape)

[[ 3]
 [ 8]
 [22]]
(3, 1)


## Array Indexing for changing elements

sometimes its important o use array of indices to acces or change elements

In [67]:
#create a 4 by 3 array
array_index=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [68]:
print(array_index)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [69]:
#craete an array of indices
col_indices=np.array([0,1,2,0])
print(col_indices)

[0 1 2 0]


In [71]:
row_indices=np.array([0,1,2,3])
print(row_indices)

[0 1 2 3]


In [73]:
#pairing the col and row indices together
for row,col in zip(row_indices,col_indices):
    print(row,',',col)

0 , 0
1 , 1
2 , 2
3 , 0


In [74]:
print(array_index)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [75]:
new_array_index=array_index[row_indices,col_indices]

In [77]:
# accesing elelments in each row
print(new_array_index)

[ 1  5  9 10]


In [80]:
# changing one element in each row
array_index[row_indices,col_indices]+=1000

In [81]:
print(array_index)

[[1001    2    3]
 [   4 1005    6]
 [   7    8 1009]
 [1010   11   12]]
