## Broadcasting

In [1]:
import numpy as np


In [2]:
arr=np.zeros((4,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
#craete a rank 1 array with 3 values
add_rows=np.array([1,0,2])
print(add_rows)

[1 0 2]


In [4]:
broadcast_arr=arr+add_rows
print(broadcast_arr)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


####  in the above cell ,the values in add row have been added to each values in the rows of arr

In [5]:
#adding to aech column of arr using broadcasting
add_col=np.array([[0,1,2,3]])
add_col=add_col.T
print(add_col)

[[0]
 [1]
 [2]
 [3]]


#### in the above cell, we are trying to create a 4 by 1 array.
#### To do so,we first create a 2d 1 by 4 then transpose it

In [8]:
#to add to each column
add_col_arr=arr+add_col
print(add_col_arr)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [11]:
add_scalar=np.array([6])
print(add_scalar)

[6]


In [12]:
#scalar braodcasts n both directions
arr2=add_scalar+arr
print(arr2)

[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]
