## Statistical Methods , Sorting and Set Operations:

### Basic Statistical Operations:

In [1]:
import numpy as np


In [7]:
#create a 2 by 4 random matrix
arr=np.random.randn(2,4)*10
print(arr)

[[ -3.25395246   7.58979418 -11.7004075    7.98353053]
 [ -2.32380961  -3.63232979  20.25664824   6.52813737]]


In [11]:
#Mean for all Elements
arr_mean=arr.mean()
print(arr_mean)

2.6809513688058653


In [12]:
#compute the row of means
mean_row=arr.mean(axis=1)
print(mean_row)

[0.15474119 5.20716155]


In [13]:
# compute the mean of column
mean_column=arr.mean(axis=0)
print(mean_column)

[-2.78888104  1.97873219  4.27812037  7.25583395]


In [14]:
#sum of all elements
sum_all=arr.sum()
print(sum_all)

21.447610950446922


In [15]:
# median of the elements in a column
med_column=np.median(arr,axis=0)
print(med_column)

[-2.78888104  1.97873219  4.27812037  7.25583395]


In [16]:
print(arr)

[[ -3.25395246   7.58979418 -11.7004075    7.98353053]
 [ -2.32380961  -3.63232979  20.25664824   6.52813737]]


In [17]:
#median of the elements in the row
med_row=np.median(arr,axis=1)
print(med_row)

[2.16792086 2.10216388]


## Sorting

In [18]:
#create a 10 random element array
unsorted_array=np.random.randn(10)
print(unsorted_array)

[ 1.43074518 -0.04999224 -0.58036908 -1.06051576  1.59845108 -0.37459795
 -0.1983521   1.93659332 -0.27687564 -0.12972858]


In [20]:
# copy the unsorted array into the sorted array variable
sorted_array=np.array(unsorted_array)


In [24]:
#sorting
print(sorted_array)

[-1.06051576 -0.58036908 -0.37459795 -0.27687564 -0.1983521  -0.12972858
 -0.04999224  1.43074518  1.59845108  1.93659332]


In [34]:
print(np.sort(sorted_array))

[-1.06051576 -0.58036908 -0.37459795 -0.27687564 -0.1983521  -0.12972858
 -0.04999224  1.43074518  1.59845108  1.93659332]


In [29]:

trial=np.array([3,1,-1,9],dtype='int64')

In [33]:
print(np.sort(trial))

[-1  1  3  9]


### Finding Unique Elements

In [35]:
array_uniq=np.array([2,5,9,8,7,2,5,7])

In [36]:
#unique elements
print(np.unique(array_uniq))

[2 5 7 8 9]


### Set Operations with np.array data type

In [37]:
s1=np.array(['desk','chair','bulb'])
s2=np.array(['lamp','bulb','chair'])
print(s1,s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [38]:
#To find elememts commo to both sets
print(np.intersect1d(s1,s2))
#we use interesct 1d becuase it expects a one dimensoal array

['bulb' 'chair']


In [39]:
# Finding unique elements in both sets
#we use union1d
print(np.union1d(s1,s2))


['bulb' 'chair' 'desk' 'lamp']


In [40]:
# Elements in set 1 taht are not in set 2
print(np.setdiff1d(s1,s2))

['desk']


In [41]:
print(np.setdiff1d(s2,s1))

['lamp']


In [42]:
#Boolean results of which elements are in s1 and also s2
print(np.in1d(s1,s2))

[False  True  True]


In [43]:
print(np.in1d(s2,s1))

[False  True  True]
